In [2]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
b = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [4]:
c = np.array([[3, 7, 2, 4, 9], [5, 1, 8, 4, 5], [6, 3, 7, 1, 8], [7, 3, 1, 8, 5], [8, 5, 7, 2, 4]])
c

array([[3, 7, 2, 4, 9],
       [5, 1, 8, 4, 5],
       [6, 3, 7, 1, 8],
       [7, 3, 1, 8, 5],
       [8, 5, 7, 2, 4]])

In [5]:
d = np.array([[0.24, 0.52, 0.78, 0.12], [0.72, 0.51, 0.28, 0.33], [0.21, 0.94, 0.48, 0.67], [0.91, 0.57, 0.42, 0.50]])
d

array([[0.24, 0.52, 0.78, 0.12],
       [0.72, 0.51, 0.28, 0.33],
       [0.21, 0.94, 0.48, 0.67],
       [0.91, 0.57, 0.42, 0.5 ]])

In [6]:
v1 = np.array([2, 7, 4, 9, 5])
v2 = np.array([6, 9, 2, 5, 3])
print(v1 + v2)
print(v1 - v2)
print(v1 * v2)

[ 8 16  6 14  8]
[-4 -2  2  4  2]
[12 63  8 45 15]


In [7]:
v1 = np.array([2, 7, 4, 9, 5, 6, 1])
v2 = np.array([6, 9, 2, 5, 3, 4, 9])
print(np.dot(v1, v2))

176


In [9]:
m1 = np.array([[2, 3], [9, 5]])
m2 = np.array([[6, 1, 4], [9, 7, 8]])
print(np.dot(m1, m2))

[[39 23 32]
 [99 44 76]]


In [10]:
m = np.array([[1, 7, 4], [5, 3, 7], [9, 4, 6]])
print(np.linalg.inv(m))

[[-0.05181347 -0.13471503  0.19170984]
 [ 0.17098446 -0.15544041  0.06735751]
 [-0.03626943  0.30569948 -0.16580311]]


In [11]:
m = np.array([[0.71, 0.67, 0.25, 0.81], [0.21, 0.48, 0.36, 0.72], [0.26, 0.62, 0.78, 0.24], [0.63, 0.93, 0.51, 0.74]])
print(m.T)

[[0.71 0.21 0.26 0.63]
 [0.67 0.48 0.62 0.93]
 [0.25 0.36 0.78 0.51]
 [0.81 0.72 0.24 0.74]]


In [12]:
m = np.array([[4, 7, 5, 4], [6, 8, 2, 5], [9, 4, 6, 2]])
v = np.array([6, 3, 6, 1])
print(m * v)

[[24 21 30  4]
 [36 24 12  5]
 [54 12 36  2]]


In [13]:
m = np.random.rand(2, 3)
v = np.random.rand(3)
print(m*v)

[[0.666087   0.07630871 0.70989008]
 [0.1091779  0.00300833 0.51733839]]


In [14]:
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))
print(m1 * m2)

[[80 35]
 [21 48]]


In [15]:
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))
print(np.dot(m1, m2))

[[24 42]
 [51 75]]


In [16]:
m = np.random.randint(1, 101, size=(5, 5))
print(m.sum())

1443


In [17]:
m1 = np.random.randint(1, 11, size=(4, 4))
m2 = np.random.randint(1, 11, size=(4, 4))
print(m1 - m2)

[[-6  3  0  6]
 [ 4  3 -6 -1]
 [-7 -3  3  2]
 [ 4 -2  4 -3]]


In [20]:
m = np.random.rand(3, 3)
v = np.array([[m[0][0] + m[0][1] + m[0][2]], [m[1][0] + m[1][1] + m[1][2]], [m[2][0] + m[2][1] + m[2][2]]])
print(v)
row_sum = np.sum(m, axis=1)
column_vector = row_sum.reshape(-1, 1)
print(column_vector)

[[2.25985805]
 [2.17157735]
 [2.10396805]]
[[2.25985805]
 [2.17157735]
 [2.10396805]]


In [21]:
m = np.random.randint(1, 101, size=(3, 4))
result = np.square(m)
print(result)

[[ 1521    64  2601  5776]
 [  676  8836  1225   625]
 [ 9025  9801 10000  2601]]


In [22]:
v = np.random.randint(1, 51, size=(1, 4))
result = np.square(v)
print(v)
print(result)

[[ 4 45 28 42]]
[[  16 2025  784 1764]]
